version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: vaadin-blog-postgres
    environment:
      POSTGRES_DB: vaadin_blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/.postgres/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
