server:
  port: ${PORT:8080}

spring:
  mustache:
    check-template-location: false

  datasource:
    url: jdbc:postgresql://localhost:5432/vaadin_blog
    username: root
    password: test_pass
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  #    hibernate:
#      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true


logging.level.org.atmosphere: warn