CREATE TABLE author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE category
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    slug           VARCHAR(255),
    excerpt        VARCHAR(255),
    publish_status VARCHAR(255),
    article_count  INTEGER,
    date_created   TIMESTAMP WITHOUT TIME ZONE,
    date_updated   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE post
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255),
    slug           VARCHAR(255),
    excerpt        VARCHAR(255),
    date_created   TIMESTAMP WITHOUT TIME ZONE,
    date_updated   TIMESTAMP WITHOUT TIME ZONE,
    published_date TIMESTAMP WITHOUT TIME ZONE,
    post_status    VARCHAR(255),
    content        TEXT,
    thumbnail_url  VARCHAR(255),
    video_id       VARCHAR(255),
    source_code    VARCHAR(255),
    post_type      VARCHAR(255),
    template_type  VARCHAR(255),
    display_order  INTEGER,
    author_id      BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE post_categories
(
    categories_id BIGINT NOT NULL,
    posts_id      BIGINT NOT NULL,
    CONSTRAINT pk_post_categories PRIMARY KEY (categories_id, posts_id)
);

CREATE TABLE post_tags
(
    posts_id BIGINT NOT NULL,
    tags_id  BIGINT NOT NULL,
    CONSTRAINT pk_post_tags PRIMARY KEY (posts_id, tags_id)
);

CREATE TABLE tag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    bio        VARCHAR(255),
    password   VARCHAR(60),
    roles      VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE post_categories
    ADD CONSTRAINT fk_poscat_on_category FOREIGN KEY (categories_id) REFERENCES category (id);

ALTER TABLE post_categories
    ADD CONSTRAINT fk_poscat_on_post FOREIGN KEY (posts_id) REFERENCES post (id);

ALTER TABLE post_tags
    ADD CONSTRAINT fk_post_tags_on_post FOREIGN KEY (posts_id) REFERENCES post (id);

ALTER TABLE post_tags
    ADD CONSTRAINT fk_post_tags_on_tag FOREIGN KEY (tags_id) REFERENCES tag (id);